# Artur Bonamigo

# token
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMTExMTExMTExMSIsImlkIjoxLCJncnVwbyI6MSwiZXhwIjoxNzc0OTE3MjExLCJ0eXBlIjoiYWNjZXNzIn0.F7L5vNBF1-dyzMPCmli3-M9zi4VqM4klKj5GC40EV_M

### Verbo GET – listar todos
GET http://localhost:8000/cliente/ HTTP/1.1
Authorization: Bearer {{access_token}}

### Verbo GET – listar um
GET http://localhost:8000/cliente/1 HTTP/1.1
Authorization: Bearer {{access_token}}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/cliente/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}
{
"nome" : "Artur Bonamigo atualizado"
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/cliente/1 HTTP/1.1
Authorization: Bearer {{access_token}}