# token
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMTExMTExMTExMSIsImlkIjoxLCJncnVwbyI6MSwiZXhwIjoxNzc1MDc1MjE2LCJ0eXBlIjoiYWNjZXNzIn0.-27qkhPUZ53FqDhRqlIyGzpwh89UzMlRBQbrdEb2idE

### Verbo GET – listar todos
GET http://localhost:8000/funcionario/ HTTP/1.1
Authorization: Bearer {{access_token}}

### Verbo GET – listar um
GET http://localhost:8000/funcionario/3 HTTP/1.1
Authorization: Bearer {{access_token}}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/funcionario/3 HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}

{
"nome" : "Zé das Batatas"
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/funcionario/1 HTTP/1.1
Authorization: Bearer {{access_token}}