# Artur Bonamigo

### Verbo GET – listar todos
GET http://localhost:8000/produto/ HTTP/1.1

### Verbo GET – listar um
GET http://localhost:8000/produto/10 HTTP/1.1

### Verbo POST – adicionar
POST http://localhost:8000/produto/ HTTP/1.1
Content-Type: application/json

{
    "nome" : "Teste",
    "descricao" : "Teste",
    "valorUnitario" : 10.00,
    "foto" : "Teste"
}

### Verbo PUT – atualiza
PUT http://localhost:8000/produto/2 HTTP/1.1
Content-Type: application/json

{
    "nome" : "Teste",
    "descricao" : "Teste",
    "valorUnitario" : 20.00,
    "foto" : "Teste"
}

### Verbo DELETE - excluir
DELETE http://localhost:8000/produto/3 HTTP/1.1